### ISSUE TITLE
Adds Court Records and Newspaper Clippings Links to Crimes Section

### ISSUE THREAD

**Issue by chrisdaaz** [nulib/homicide-in-chicago#51]
The Crimes section of the website contains a right sidebar that lists related Court Records and Newspaper Clippings. 

![image](https://user-images.githubusercontent.com/24395592/58656567-2666c580-82e2-11e9-8518-33c530cf99bf.png)

This is true for every page that's linked from the `Crimes of the Century` section, which is located in the Hugo project within the `/content/crimes/` directory. Each page on the site has a corresponding `.md` file. 

### Steps

- Open up a markdown file from the `/content/crimes/` section
- Find the corresponding page on [the original website](http://homicide.northwestern.edu/crimes/)
- Add the sidebar link information at the top of the markdown file in the YAML front-matter, whereby "Newspaper Clippings" = `news_clips` and "Court Records" = `court_records`. The `title` field corresponds to the title of the link and the `url` field corresponds to the link location (hint: on the original wesbite, you can right-click --> "Copy Link Location" to grab the URL and paste it into the `url:` field; however, you must delete everything _before_ `/docs_fk/`)

```
court_records:
  - title: "2 Others of Auto Party Slain in Cicero Killing"
    url: /docs_fk/homicide/7349/McSwiggin05.jpg
  - title: "Assassinate Aid of Crowe"
    url: /docs_fk/homicide/7349/McSwiggin04.jpg
  - title: "Bare M'Swiggin Death Tale"
    url: /docs_fk/homicide/7349/McSwiggin00.jpg
news_clips:
  - title: [LINK TITLE]
    url: [LINK URL]
  - title: [LINK TITLE]
    url: [LINK URL]
  - title: [LINK TITLE]
    url: [LINK URL]
```
- Only add entries for what's on the page on the original site. Don't add YAML entries for "Court Records" if there aren't any on the page.

### Done looks like
- [ ] All of the markdown files in `/content/crimes/` have YAML entries in the front-matter for Court Records and/or Newspaper Clippings as appropriate.
- [ ] A PR is submitted when complete

### Note
If you don't finish in your shift, add a comment to this issue stating where you left off. You can publish your branch at any time and make commits to save your work. PR when done.
